import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Step1 from "../src/Step1";
import Step2 from "../src/Step2";

export default function Home() {

  const [stepCount,setStepCount] = useState(1);
  
  const nextStep = () => {
    setStepCount(stepCount + 1);
  };

  return (
    <>
      <Head>
        <title>Racingnews Tacotron</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {stepCount == 1 ? <Step1 nextStepFunc={nextStep}/> : <></>}
      {stepCount == 2 ? <Step2 /> : <></>}

    </>
  )
}
